export const REQUEST_SEATS = "REQUEST_SEATS";
export const RECEIVE_SEATS = "RECEIVE_SEATS";
export const FAILED_SEATS = "FAILED_SEATS";
export const SELECTED_SEAT = "SELECTED_SEAT";
export const UNSELECTED_SEAT = "UNSELECTED_SEAT";
export const CLEAR_SELECTED = "CLEAR_SELECTED";
